version: '3.8'

services:
  app:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    container_name: taskmanager_app
    command: python manage.py run --env development
    environment:
      - FLASK_ENV=development
    env_file:
      - ../env/.env.dev
    volumes:
      - ..:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    networks:
      - taskmanager_network

  db:
    image: postgres:15-alpine
    container_name: taskmanager_db
    environment:
      POSTGRES_DB: taskmanager_dev
      POSTGRES_USER: taskmanager
      POSTGRES_PASSWORD: taskmanager123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - taskmanager_network

  redis:
    image: redis:7-alpine
    container_name: taskmanager_redis
    ports:
      - "6379:6379"
    networks:
      - taskmanager_network

volumes:
  postgres_data:

networks:
  taskmanager_network:
    driver: bridge